/**
 * API route to get membership data
 *
 * Data structure:
 *   data/{year}/{month}/members.json           ← merged (generated by fetch-members script)
 *   data/{year}/{month}/stripe/subscriptions.json
 *   data/{year}/{month}/odoo/subscriptions.json
 *
 * For the current month, if members.json is stale (>1h) and Odoo is configured,
 * we re-merge from provider snapshots + live Odoo data.
 *
 * GET /api/members              → current month
 * GET /api/members?year=2026&month=01 → specific month
 */

import { NextResponse } from "next/server";
import * as fs from "fs";
import * as path from "path";
import * as crypto from "crypto";
import type { Member, MembersFile, MembersSummary, Amount } from "@/types/members";
import settings from "@/settings/settings.json";

const DATA_DIR = process.env.DATA_DIR || path.join(process.cwd(), "data");
const ODOO_CACHE_TTL = 5 * 60 * 1000; // 5 min
const ODOO_CONFIG = settings.membership.odoo;

// ─── Helpers ────────────────────────────────────────────────────────────────

function amt(value: number, currency = "EUR", decimals = 2): Amount {
  return { value, decimals, currency };
}

function recalcSummary(members: Member[]): MembersSummary {
  const active = members.filter((m) => m.status === "active" || m.status === "trialing");
  const monthly = active.filter((m) => m.plan === "monthly");
  const yearly = active.filter((m) => m.plan === "yearly");
  const mrr = monthly.reduce((s, m) => s + m.amount.value, 0) +
    yearly.reduce((s, m) => s + m.amount.value / 12, 0);
  return {
    totalMembers: members.length,
    activeMembers: active.length,
    monthlyMembers: monthly.length,
    yearlyMembers: yearly.length,
    mrr: amt(Math.round(mrr * 100) / 100),
  };
}

// ─── Live Odoo fetch (for current month freshness) ──────────────────────────

let odooCache: { members: Member[]; at: number } | null = null;

async function fetchLiveOdooMembers(): Promise<Member[]> {
  const apiKey = process.env.ODOO_API_KEY;
  const login = process.env.ODOO_LOGIN;
  if (!apiKey || !login) return [];

  if (odooCache && Date.now() - odooCache.at < ODOO_CACHE_TTL) return odooCache.members;

  try {
    async function rpc(service: string, method: string, args: any[]): Promise<any> {
      const res = await fetch(`${ODOO_CONFIG.url}/jsonrpc`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ jsonrpc: "2.0", id: Date.now(), method: "call", params: { service, method, args } }),
      });
      const d = await res.json();
      if (d.error) throw new Error(d.error.data?.message || d.error.message);
      return d.result;
    }

    const uid = await rpc("common", "authenticate", [ODOO_CONFIG.db, login, apiKey, {}]);
    if (!uid) throw new Error("Odoo auth failed");

    async function exec(model: string, method: string, args: any[], kw: any = {}): Promise<any> {
      return rpc("object", "execute_kw", [ODOO_CONFIG.db, uid, apiKey, model, method, args, kw]);
    }

    const tmplIds = ODOO_CONFIG.products.map((p: any) => p.id);
    const ppIds: number[] = await exec("product.product", "search", [[["product_tmpl_id", "in", tmplIds]]]);
    if (!ppIds.length) { odooCache = { members: [], at: Date.now() }; return []; }

    const orderIds: number[] = await exec("sale.order", "search", [[
      ["is_subscription", "=", true],
      ["order_line.product_id", "in", ppIds],
      ["subscription_state", "in", ["3_progress", "4_paused"]],
    ]]);
    if (!orderIds.length) { odooCache = { members: [], at: Date.now() }; return []; }

    const orders = await exec("sale.order", "read", [orderIds], {
      fields: ["partner_id", "subscription_state", "recurring_monthly", "start_date", "next_invoice_date", "order_line"],
    });

    const partnerIds = [...new Set(orders.map((o: any) => o.partner_id[0]))];
    const partners = await exec("res.partner", "read", [partnerIds], { fields: ["name", "email", "is_company"] });
    const pm = new Map(partners.map((p: any) => [p.id, p]));

    // Resolve order → product template
    const allLines = orders.flatMap((o: any) => o.order_line);
    const lines = allLines.length ? await exec("sale.order.line", "read", [allLines], { fields: ["product_id", "order_id"] }) : [];
    const ppProductIds = [...new Set(lines.map((l: any) => l.product_id[0]))];
    const pps = ppProductIds.length ? await exec("product.product", "read", [ppProductIds], { fields: ["product_tmpl_id"] }) : [];
    const ppToTmpl = new Map(pps.map((p: any) => [p.id, p.product_tmpl_id[0]]));

    const o2t = new Map<number, number>();
    for (const l of lines) {
      const t = ppToTmpl.get(l.product_id[0]);
      if (t && tmplIds.includes(t)) o2t.set(l.order_id[0], t);
    }

    const salt = process.env.EMAIL_HASH_SALT || "dev-default";
    const members: Member[] = [];

    for (const order of orders) {
      const partner = pm.get(order.partner_id[0]);
      if (!partner) continue;
      const email = partner.email || "";
      const emailHash = email
        ? crypto.createHash("sha256").update(email.toLowerCase().trim() + salt).digest("hex")
        : `odoo-${order.id}`;

      const tmplId = o2t.get(order.id);
      const pc = ODOO_CONFIG.products.find((p: any) => p.id === tmplId);
      const interval = (pc?.interval || "month") as "month" | "year";

      members.push({
        id: `odoo-${order.id}`,
        source: "odoo",
        accounts: { emailHash },
        firstName: (partner.name || "Member").split(/\s+/)[0],
        plan: interval === "year" ? "yearly" : "monthly",
        amount: amt(order.recurring_monthly * (interval === "year" ? 12 : 1)),
        interval,
        status: order.subscription_state === "4_paused" ? "paused" : "active",
        currentPeriodStart: order.start_date || "",
        currentPeriodEnd: order.next_invoice_date || "",
        latestPayment: null,
        createdAt: order.start_date || "",
        isOrganization: tmplId === 104 || partner.is_company,
      });
    }

    odooCache = { members, at: Date.now() };
    return members;
  } catch (err) {
    console.error("Odoo live fetch error:", err);
    return odooCache?.members || [];
  }
}

// ─── Route ──────────────────────────────────────────────────────────────────

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const now = new Date();
  const year = searchParams.get("year") || String(now.getFullYear());
  const month = (searchParams.get("month") || String(now.getMonth() + 1)).padStart(2, "0");
  const monthDir = path.join(DATA_DIR, year, month);

  // Try loading pre-merged members.json
  const membersPath = path.join(monthDir, "members.json");
  let data: MembersFile | null = null;

  if (fs.existsSync(membersPath)) {
    try {
      data = JSON.parse(fs.readFileSync(membersPath, "utf-8"));
    } catch {}
  }

  // For current month: enrich with live Odoo data
  const isCurrentMonth = year === String(now.getFullYear()) && month === String(now.getMonth() + 1).padStart(2, "0");

  if (isCurrentMonth) {
    const odooMembers = await fetchLiveOdooMembers();

    if (odooMembers.length > 0) {
      const stripeMembers = (data?.members || []).map((m) => ({ ...m, source: m.source || ("stripe" as const) }));
      const emailHashes = new Set(stripeMembers.map((m) => m.accounts.emailHash));
      const uniqueOdoo = odooMembers.filter((m) => !emailHashes.has(m.accounts.emailHash));
      const allMembers = [...stripeMembers, ...uniqueOdoo];

      data = {
        year,
        month,
        productId: "mixed",
        generatedAt: new Date().toISOString(),
        summary: recalcSummary(allMembers),
        members: allMembers,
      };
    }
  }

  if (!data) {
    return NextResponse.json({ error: "Members data not found for this month" }, { status: 404 });
  }

  return NextResponse.json(data);
}
