import { NextRequest, NextResponse } from "next/server";
import * as fs from "fs";
import * as path from "path";
import { DATA_DIR } from "@/lib/data-paths";
import { saveEventMetadataOverlay } from "@/lib/event-metadata-overlay";

interface EventMetadataUpdate {
  id: string;
  metadata: {
    host?: string;
    attendance?: number;
    ticketRevenue?: number;
    fridgeIncome?: number;
    rentalIncome?: number;
    ticketsSold?: number;
    note?: string;
  };
}

interface RequestBody {
  year: string;
  month: string;
  events: EventMetadataUpdate[];
}

export async function POST(request: NextRequest) {
  try {
    const body: RequestBody = await request.json();
    const { year, month, events: updatedEvents } = body;

    // Validate input
    if (!year || !month || !updatedEvents) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    // The month must exist in the dataset. Either layout is fine: the pipeline
    // writes generated/events.json, older snapshots have events.json.
    const monthExists = [
      path.join(DATA_DIR, year, month, "generated", "events.json"),
      path.join(DATA_DIR, year, month, "events.json"),
    ].some((candidate) => fs.existsSync(candidate));

    if (!monthExists) {
      return NextResponse.json(
        { error: "Events file not found" },
        { status: 404 }
      );
    }

    // DATA_DIR is read-only and regenerated by the chb pipeline, so the edits
    // go to an overlay that is merged over the events when they are read.
    const updates = Object.fromEntries(
      updatedEvents.map((e) => [e.id, e.metadata])
    );

    if (!saveEventMetadataOverlay(year, month, updates)) {
      return NextResponse.json(
        { error: "Could not persist event metadata" },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Error updating event metadata:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
