/**
 * File-backed, append-only store for proposals.
 *
 * Each proposal is a directory holding `events.jsonl`; the proposal you read is
 * the projection of that log. Append-only is what makes the thread honest: a
 * revision never overwrites what people were reacting to, it appends a new
 * version, and the diff between them is derived rather than remembered.
 *
 * The dataset the rest of the site reads (DATA_DIR) is generated by the chb
 * pipeline and treated as read-only, so proposals live in their own directory.
 */

import * as fs from "fs";
import * as path from "path";
import type {
  Attachment,
  Audience,
  Contribution,
  Proposal,
  ProposalComment,
  ProposalDraft,
  ProposalStatus,
  Reaction,
  Refund,
  Revision,
  Rsvp,
  Slot,
  TicketPricing,
} from "./types";
import { bookedHours, fundingProgress, fundingTarget, getRoom } from "./funding";
import { prettyField, visibleChange } from "./diff-labels";

export const PROPOSALS_DIR =
  process.env.PROPOSALS_DIR || path.join(process.cwd(), ".data", "proposals");

// ── the log ────────────────────────────────────────────────────────────────

export type ProposalEvent =
  | { type: "created"; at: string; actorId: string; actorName: string; proposal: Proposal }
  | {
      type: "revised";
      at: string;
      actorId: string;
      actorName: string;
      patch: Partial<Proposal>;
      changes: Revision["changes"];
    }
  | { type: "commented"; at: string; comment: ProposalComment }
  | { type: "contributed"; at: string; contribution: Contribution }
  | { type: "rsvped"; at: string; rsvp: Rsvp }
  | { type: "tasklist_linked"; at: string; taskListId: string }
  | { type: "refunded"; at: string; refunds: Refund[]; note?: string }
  | { type: "reacted"; at: string; reaction: Reaction }
  | { type: "numbered"; at: string; number: number; slug: string; eventSlug?: string }
  | {
      type: "status_changed";
      at: string;
      actorId: string;
      actorName: string;
      status: ProposalStatus;
      note?: string;
      confirmedSlotId?: string | null;
    };

function proposalDir(id: string): string {
  return path.join(PROPOSALS_DIR, id);
}

function logPath(id: string): string {
  return path.join(proposalDir(id), "events.jsonl");
}

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

export function appendEvent(id: string, event: ProposalEvent): void {
  ensureDir(proposalDir(id));
  fs.appendFileSync(logPath(id), JSON.stringify(event) + "\n", "utf-8");
}

function readLog(id: string): ProposalEvent[] {
  const file = logPath(id);
  if (!fs.existsSync(file)) return [];
  return fs
    .readFileSync(file, "utf-8")
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      try {
        return JSON.parse(line) as ProposalEvent;
      } catch {
        return null;
      }
    })
    .filter((e): e is ProposalEvent => e !== null);
}

// ── projection ─────────────────────────────────────────────────────────────

function project(events: ProposalEvent[]): Proposal | null {
  const first = events[0];
  if (!first || first.type !== "created") return null;
  // Proposals written before a field existed are read with a sane default
  // rather than migrated in place — the log is append-only.
  let proposal: Proposal = {
    ...first.proposal,
    refunds: first.proposal.refunds ?? [],
    number: first.proposal.number ?? 0,
    eventSlug: first.proposal.eventSlug ?? first.proposal.slug,
    link: first.proposal.link ?? null,
    reactions: first.proposal.reactions ?? [],
    minAttendees: first.proposal.minAttendees ?? null,
    maxAttendees: first.proposal.maxAttendees ?? null,
  };

  for (const event of events.slice(1)) {
    switch (event.type) {
      case "revised": {
        proposal = {
          ...proposal,
          ...event.patch,
          version: proposal.version + 1,
          updatedAt: event.at,
          revisions: [
            ...proposal.revisions,
            {
              version: proposal.version + 1,
              authorId: event.actorId,
              authorName: event.actorName,
              createdAt: event.at,
              changes: event.changes,
            },
          ],
        };
        break;
      }
      case "commented":
        proposal = { ...proposal, comments: [...proposal.comments, event.comment] };
        break;
      case "contributed":
        proposal = {
          ...proposal,
          contributions: [...proposal.contributions, event.contribution],
        };
        break;
      case "rsvped": {
        const others = proposal.rsvps.filter(
          (r) => r.contributorId !== event.rsvp.contributorId,
        );
        proposal = { ...proposal, rsvps: [...others, event.rsvp] };
        break;
      }
      case "tasklist_linked":
        proposal = { ...proposal, taskListId: event.taskListId };
        break;
      case "refunded":
        proposal = { ...proposal, refunds: [...proposal.refunds, ...event.refunds] };
        break;
      case "reacted": {
        // Same person, same target, same emoji again = taking it back.
        const { reaction } = event;
        const existing = proposal.reactions.findIndex(
          (r) =>
            r.actorId === reaction.actorId &&
            r.targetId === reaction.targetId &&
            r.emoji === reaction.emoji,
        );
        proposal = {
          ...proposal,
          reactions:
            existing >= 0
              ? proposal.reactions.filter((_, i) => i !== existing)
              : [...proposal.reactions, reaction],
        };
        break;
      }
      case "numbered":
        proposal = {
          ...proposal,
          number: event.number,
          slug: event.slug,
          eventSlug: event.eventSlug ?? proposal.eventSlug,
        };
        break;
      case "status_changed":
        proposal = {
          ...proposal,
          status: event.status,
          decidedBy: event.actorName,
          decidedAt: event.at,
          decisionNote: event.note,
          confirmedSlotId:
            event.confirmedSlotId !== undefined
              ? event.confirmedSlotId
              : proposal.confirmedSlotId,
          updatedAt: event.at,
        };
        break;
    }
  }

  return withDerivedStatus(proposal);
}

/**
 * A proposal that reaches its funding target moves itself to `funded`, which is
 * what unlocks the steward's confirm button. It never confirms itself — putting
 * an event on the calendar holds a room, and that stays a human decision.
 */
function withDerivedStatus(proposal: Proposal): Proposal {
  if (proposal.status !== "open") return proposal;
  const progress = progressFor(proposal);
  return progress.funded ? { ...proposal, status: "funded" } : proposal;
}

export function progressFor(proposal: Proposal) {
  const hours = bookedHours(proposal.slots, proposal.confirmedSlotId);
  const target = fundingTarget({
    roomSlug: proposal.roomSlug,
    hours,
    expectedPeople: proposal.expectedPeople,
  });
  return fundingProgress(target, proposal.contributions);
}

// ── reads ──────────────────────────────────────────────────────────────────

export function listProposalIds(): string[] {
  if (!fs.existsSync(PROPOSALS_DIR)) return [];
  return fs
    .readdirSync(PROPOSALS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name);
}

/** Accepts an id, a slug, "7-repair-cafe", or plain "7". */
export function getProposal(idOrSlugOrNumber: string): Proposal | null {
  const direct = project(readLog(idOrSlugOrNumber));
  if (direct) return direct;

  const asNumber = /^\d+$/.test(idOrSlugOrNumber) ? parseInt(idOrSlugOrNumber, 10) : null;
  const leadingNumber = /^(\d+)-/.exec(idOrSlugOrNumber);
  const number = asNumber ?? (leadingNumber ? parseInt(leadingNumber[1], 10) : null);

  for (const id of listProposalIds()) {
    const proposal = project(readLog(id));
    if (!proposal) continue;
    if (proposal.slug === idOrSlugOrNumber) return proposal;
    if (proposal.eventSlug === idOrSlugOrNumber) return proposal;
    if (number !== null && proposal.number === number) return proposal;
  }
  return null;
}

/**
 * Bring older records up to date: give a number to anything written before
 * proposals had one (oldest first, so the numbering still reads as the order
 * they were proposed in), and a readable event URL to anything still carrying
 * the old random-suffix slug.
 */
export function tidyLegacyUrls(): void {
  const all = listProposalIds()
    .map((id) => project(readLog(id)))
    .filter((p): p is Proposal => p !== null)
    .sort((a, b) => (a.createdAt < b.createdAt ? -1 : 1));

  const takenSlugs = new Set(all.map((p) => p.eventSlug));

  for (const proposal of all) {
    const base = slugify(proposal.title) || "event";
    const number = proposal.number || nextNumber();
    const wanted = takenSlugs.has(base) && proposal.eventSlug !== base ? `${base}-${number}` : base;

    const needsNumber = !proposal.number;
    const needsSlug = proposal.eventSlug !== wanted;
    if (!needsNumber && !needsSlug) continue;

    takenSlugs.delete(proposal.eventSlug);
    takenSlugs.add(wanted);

    appendEvent(proposal.id, {
      type: "numbered",
      at: new Date().toISOString(),
      number,
      slug: `${number}-${base}`,
      eventSlug: wanted,
    });
  }
}

/** @deprecated use tidyLegacyUrls */
export const numberUnnumbered = tidyLegacyUrls;

export function listProposals(options?: { includeDrafts?: boolean }): Proposal[] {
  const all = listProposalIds()
    .map((id) => project(readLog(id)))
    .filter((p): p is Proposal => p !== null);
  const visible = options?.includeDrafts ? all : all.filter((p) => p.status !== "draft");
  return visible.sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1));
}

// ── writes ─────────────────────────────────────────────────────────────────

function slugify(title: string): string {
  return title
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}

function shortId(): string {
  return Math.random().toString(36).slice(2, 8) + Date.now().toString(36).slice(-4);
}

/**
 * The next proposal number. Proposals are numbered like issues — #7 is easier
 * to say out loud, and to put in a URL, than a random id.
 */
function nextNumber(): number {
  const counterFile = path.join(PROPOSALS_DIR, "counter.json");
  ensureDir(PROPOSALS_DIR);
  let current = 0;
  if (fs.existsSync(counterFile)) {
    try {
      current = JSON.parse(fs.readFileSync(counterFile, "utf-8")).last ?? 0;
    } catch {
      current = 0;
    }
  }
  // Never hand out a number already in use, even if the counter went missing.
  const used = listProposals({ includeDrafts: true }).map((p) => p.number ?? 0);
  const next = Math.max(current, ...used, 0) + 1;
  fs.writeFileSync(counterFile, JSON.stringify({ last: next }), "utf-8");
  return next;
}

export function createProposal(
  draft: ProposalDraft,
  author: { id: string; name: string },
  options?: { status?: ProposalStatus },
): Proposal {
  const id = shortId();
  const number = nextNumber();
  const now = new Date().toISOString();
  const slots: Slot[] = draft.slots.map((s, i) => ({ ...s, id: `s${i + 1}` }));

  const base = slugify(draft.title) || "event";
  const taken = listProposals({ includeDrafts: true }).some((p) => p.eventSlug === base);

  const proposal: Proposal = {
    id,
    number,
    slug: `${number}-${base}`,
    // A readable URL for the event; the number keeps it unique if two events
    // end up with the same name.
    eventSlug: taken ? `${base}-${number}` : base,
    version: 1,
    status: options?.status ?? "open",
    title: draft.title,
    pitch: "",
    description: draft.description,
    link: draft.link,
    slots,
    confirmedSlotId: slots.length === 1 ? slots[0].id : null,
    roomSlug: draft.roomSlug,
    expectedPeople: draft.expectedPeople,
    minAttendees: draft.minAttendees,
    maxAttendees: draft.maxAttendees,
    audience: draft.audience,
    tickets: draft.tickets,
    taskListId: null,
    proposerId: author.id,
    proposerName: author.name,
    createdAt: now,
    updatedAt: now,
    comments: [],
    contributions: [],
    refunds: [],
    reactions: [],
    rsvps: [],
    revisions: [],
  };

  appendEvent(id, { type: "created", at: now, actorId: author.id, actorName: author.name, proposal });
  return proposal;
}

/**
 * Field-by-field diff, in words a reader recognises: room slugs become room
 * names, audiences read as sentences, long text is trimmed. What the thread
 * shows is exactly what is stored.
 */
export function diffProposal(before: Proposal, patch: Partial<Proposal>): Revision["changes"] {
  const changes: Revision["changes"] = [];
  const describe = (field: string, value: unknown): string => {
    if (value === null || value === undefined) return field === "roomSlug" ? "any room" : "—";
    if (field === "slots") {
      return (value as Slot[]).map((s) => `${s.date} ${s.start} (${s.duration}h)`).join(" · ");
    }
    if (field === "roomSlug") {
      return getRoom(String(value))?.name ?? String(value);
    }
    if (field === "audience") {
      return value === "public"
        ? "open to everyone"
        : value === "members"
          ? "members only"
          : "invite only";
    }
    if (field === "tickets") {
      const t = value as TicketPricing;
      if (!t.eur && !t.tokens) return "free";
      return [
        t.eur ? `€${t.eur}` : null,
        t.tokens ? `${t.tokens} tokens` : null,
        t.freeForMembers ? "free for members" : null,
      ]
        .filter(Boolean)
        .join(" · ");
    }
    const text = String(value);
    return text.length > 80 ? `${text.slice(0, 77)}…` : text;
  };

  for (const [field, value] of Object.entries(patch)) {
    if (!visibleChange(field)) continue;
    const from = describe(field, (before as unknown as Record<string, unknown>)[field]);
    const to = describe(field, value);
    if (from !== to) changes.push({ field: prettyField(field), from, to });
  }
  return changes;
}

export function reviseProposal(
  id: string,
  patch: Partial<Proposal>,
  actor: { id: string; name: string },
): Proposal | null {
  const before = getProposal(id);
  if (!before) return null;
  const changes = diffProposal(before, patch);
  if (!changes.length) return before;
  appendEvent(before.id, {
    type: "revised",
    at: new Date().toISOString(),
    actorId: actor.id,
    actorName: actor.name,
    patch,
    changes,
  });
  return getProposal(before.id);
}

export function addComment(
  id: string,
  body: string,
  author: { id: string; name: string },
  attachments?: Attachment[],
): ProposalComment | null {
  const proposal = getProposal(id);
  if (!proposal) return null;
  const comment: ProposalComment = {
    id: shortId(),
    authorId: author.id,
    authorName: author.name,
    body,
    ...(attachments && attachments.length ? { attachments } : {}),
    createdAt: new Date().toISOString(),
  };
  appendEvent(proposal.id, { type: "commented", at: comment.createdAt, comment });
  return comment;
}

export function addContribution(
  id: string,
  contribution: Omit<Contribution, "id" | "createdAt">,
): Contribution | null {
  const proposal = getProposal(id);
  if (!proposal) return null;
  const record: Contribution = {
    ...contribution,
    id: shortId(),
    createdAt: new Date().toISOString(),
  };
  appendEvent(proposal.id, { type: "contributed", at: record.createdAt, contribution: record });
  return record;
}

export function setRsvp(id: string, rsvp: Omit<Rsvp, "createdAt">): Rsvp | null {
  const proposal = getProposal(id);
  if (!proposal) return null;
  const record: Rsvp = { ...rsvp, createdAt: new Date().toISOString() };
  appendEvent(proposal.id, { type: "rsvped", at: record.createdAt, rsvp: record });
  return record;
}

export function linkTaskList(id: string, taskListId: string): void {
  const proposal = getProposal(id);
  if (!proposal) return;
  appendEvent(proposal.id, {
    type: "tasklist_linked",
    at: new Date().toISOString(),
    taskListId,
  });
}

export function toggleReaction(
  id: string,
  targetId: string,
  emoji: string,
  actor: { id: string; name: string },
): Proposal | null {
  const proposal = getProposal(id);
  if (!proposal) return null;
  appendEvent(proposal.id, {
    type: "reacted",
    at: new Date().toISOString(),
    reaction: {
      targetId,
      emoji,
      actorId: actor.id,
      actorName: actor.name,
      createdAt: new Date().toISOString(),
    },
  });
  return getProposal(proposal.id);
}

/** Reactions on one target, grouped per emoji, with whether `viewerId` is in. */
export function reactionsFor(
  proposal: Proposal,
  targetId: string,
  viewerId?: string | null,
): Array<{ emoji: string; count: number; names: string[]; mine: boolean }> {
  const groups = new Map<string, { names: string[]; mine: boolean }>();
  for (const reaction of proposal.reactions) {
    if (reaction.targetId !== targetId) continue;
    const group = groups.get(reaction.emoji) ?? { names: [], mine: false };
    group.names.push(reaction.actorName);
    if (viewerId && reaction.actorId === viewerId) group.mine = true;
    groups.set(reaction.emoji, group);
  }
  return Array.from(groups.entries()).map(([emoji, g]) => ({
    emoji,
    count: g.names.length,
    names: g.names,
    mine: g.mine,
  }));
}

export function recordRefunds(id: string, refunds: Refund[], note?: string): Proposal | null {
  const proposal = getProposal(id);
  if (!proposal || refunds.length === 0) return proposal;
  appendEvent(proposal.id, {
    type: "refunded",
    at: new Date().toISOString(),
    refunds,
    note,
  });
  return getProposal(proposal.id);
}

export function setStatus(
  id: string,
  status: ProposalStatus,
  actor: { id: string; name: string },
  options?: { note?: string; confirmedSlotId?: string | null },
): Proposal | null {
  const proposal = getProposal(id);
  if (!proposal) return null;
  appendEvent(proposal.id, {
    type: "status_changed",
    at: new Date().toISOString(),
    actorId: actor.id,
    actorName: actor.name,
    status,
    note: options?.note,
    confirmedSlotId: options?.confirmedSlotId,
  });
  return getProposal(proposal.id);
}

/** The thread: comments, revisions, contributions and decisions in one timeline. */
export type TimelineItem =
  | { kind: "comment"; at: string; comment: ProposalComment }
  | { kind: "revision"; at: string; revision: Revision }
  | { kind: "contribution"; at: string; contribution: Contribution }
  | { kind: "rsvp"; at: string; rsvp: Rsvp }
  | { kind: "status"; at: string; status: ProposalStatus; by: string; note?: string }
  | { kind: "refund"; at: string; refunds: Refund[]; note?: string };

export function timelineFor(proposal: Proposal): TimelineItem[] {
  const events = readLog(proposal.id);
  const items: TimelineItem[] = [];
  for (const event of events) {
    switch (event.type) {
      case "commented":
        items.push({ kind: "comment", at: event.at, comment: event.comment });
        break;
      case "contributed":
        items.push({ kind: "contribution", at: event.at, contribution: event.contribution });
        break;
      case "rsvped":
        items.push({ kind: "rsvp", at: event.at, rsvp: event.rsvp });
        break;
      case "refunded":
        items.push({ kind: "refund", at: event.at, refunds: event.refunds, note: event.note });
        break;
      case "status_changed":
        items.push({
          kind: "status",
          at: event.at,
          status: event.status,
          by: event.actorName,
          note: event.note,
        });
        break;
      case "revised": {
        const version =
          items.filter((i) => i.kind === "revision").length + 2; // v1 is the original
        items.push({
          kind: "revision",
          at: event.at,
          revision: {
            version,
            authorId: event.actorId,
            authorName: event.actorName,
            createdAt: event.at,
            changes: event.changes,
          },
        });
        break;
      }
    }
  }
  return items.sort((a, b) => (a.at < b.at ? -1 : 1));
}

export type { Audience };
