/**
 * File-backed, append-only store for proposals.
 *
 * Each proposal is a directory holding `events.jsonl`; the proposal you read is
 * the projection of that log. Append-only is what makes the thread honest: a
 * revision never overwrites what people were reacting to, it appends a new
 * version, and the diff between them is derived rather than remembered.
 *
 * The dataset the rest of the site reads (DATA_DIR) is generated by the chb
 * pipeline and treated as read-only, so proposals live in their own directory.
 */

import * as fs from "fs";
import * as path from "path";
import type {
  Audience,
  Contribution,
  Proposal,
  ProposalComment,
  ProposalDraft,
  ProposalStatus,
  Revision,
  Rsvp,
  Slot,
  TicketPricing,
} from "./types";
import { bookedHours, fundingProgress, fundingTarget } from "./funding";

export const PROPOSALS_DIR =
  process.env.PROPOSALS_DIR || path.join(process.cwd(), ".data", "proposals");

// ── the log ────────────────────────────────────────────────────────────────

export type ProposalEvent =
  | { type: "created"; at: string; actorId: string; actorName: string; proposal: Proposal }
  | {
      type: "revised";
      at: string;
      actorId: string;
      actorName: string;
      patch: Partial<Proposal>;
      changes: Revision["changes"];
    }
  | { type: "commented"; at: string; comment: ProposalComment }
  | { type: "contributed"; at: string; contribution: Contribution }
  | { type: "rsvped"; at: string; rsvp: Rsvp }
  | { type: "tasklist_linked"; at: string; taskListId: string }
  | {
      type: "status_changed";
      at: string;
      actorId: string;
      actorName: string;
      status: ProposalStatus;
      note?: string;
      confirmedSlotId?: string | null;
    };

function proposalDir(id: string): string {
  return path.join(PROPOSALS_DIR, id);
}

function logPath(id: string): string {
  return path.join(proposalDir(id), "events.jsonl");
}

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

export function appendEvent(id: string, event: ProposalEvent): void {
  ensureDir(proposalDir(id));
  fs.appendFileSync(logPath(id), JSON.stringify(event) + "\n", "utf-8");
}

function readLog(id: string): ProposalEvent[] {
  const file = logPath(id);
  if (!fs.existsSync(file)) return [];
  return fs
    .readFileSync(file, "utf-8")
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      try {
        return JSON.parse(line) as ProposalEvent;
      } catch {
        return null;
      }
    })
    .filter((e): e is ProposalEvent => e !== null);
}

// ── projection ─────────────────────────────────────────────────────────────

function project(events: ProposalEvent[]): Proposal | null {
  const first = events[0];
  if (!first || first.type !== "created") return null;
  let proposal: Proposal = { ...first.proposal };

  for (const event of events.slice(1)) {
    switch (event.type) {
      case "revised": {
        proposal = {
          ...proposal,
          ...event.patch,
          version: proposal.version + 1,
          updatedAt: event.at,
          revisions: [
            ...proposal.revisions,
            {
              version: proposal.version + 1,
              authorId: event.actorId,
              authorName: event.actorName,
              createdAt: event.at,
              changes: event.changes,
            },
          ],
        };
        break;
      }
      case "commented":
        proposal = { ...proposal, comments: [...proposal.comments, event.comment] };
        break;
      case "contributed":
        proposal = {
          ...proposal,
          contributions: [...proposal.contributions, event.contribution],
        };
        break;
      case "rsvped": {
        const others = proposal.rsvps.filter(
          (r) => r.contributorId !== event.rsvp.contributorId,
        );
        proposal = { ...proposal, rsvps: [...others, event.rsvp] };
        break;
      }
      case "tasklist_linked":
        proposal = { ...proposal, taskListId: event.taskListId };
        break;
      case "status_changed":
        proposal = {
          ...proposal,
          status: event.status,
          decidedBy: event.actorName,
          decidedAt: event.at,
          decisionNote: event.note,
          confirmedSlotId:
            event.confirmedSlotId !== undefined
              ? event.confirmedSlotId
              : proposal.confirmedSlotId,
          updatedAt: event.at,
        };
        break;
    }
  }

  return withDerivedStatus(proposal);
}

/**
 * A proposal that reaches its funding target moves itself to `funded`, which is
 * what unlocks the steward's confirm button. It never confirms itself — putting
 * an event on the calendar holds a room, and that stays a human decision.
 */
function withDerivedStatus(proposal: Proposal): Proposal {
  if (proposal.status !== "open") return proposal;
  const progress = progressFor(proposal);
  return progress.funded ? { ...proposal, status: "funded" } : proposal;
}

export function progressFor(proposal: Proposal) {
  const hours = bookedHours(proposal.slots, proposal.confirmedSlotId);
  const target = fundingTarget({
    roomSlug: proposal.roomSlug,
    hours,
    expectedPeople: proposal.expectedPeople,
  });
  return fundingProgress(target, proposal.contributions);
}

// ── reads ──────────────────────────────────────────────────────────────────

export function listProposalIds(): string[] {
  if (!fs.existsSync(PROPOSALS_DIR)) return [];
  return fs
    .readdirSync(PROPOSALS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name);
}

export function getProposal(idOrSlug: string): Proposal | null {
  const direct = project(readLog(idOrSlug));
  if (direct) return direct;
  for (const id of listProposalIds()) {
    const proposal = project(readLog(id));
    if (proposal && proposal.slug === idOrSlug) return proposal;
  }
  return null;
}

export function listProposals(options?: { includeDrafts?: boolean }): Proposal[] {
  const all = listProposalIds()
    .map((id) => project(readLog(id)))
    .filter((p): p is Proposal => p !== null);
  const visible = options?.includeDrafts ? all : all.filter((p) => p.status !== "draft");
  return visible.sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1));
}

// ── writes ─────────────────────────────────────────────────────────────────

function slugify(title: string): string {
  return title
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}

function shortId(): string {
  return Math.random().toString(36).slice(2, 8) + Date.now().toString(36).slice(-4);
}

export function createProposal(
  draft: ProposalDraft,
  author: { id: string; name: string },
  options?: { status?: ProposalStatus },
): Proposal {
  const id = shortId();
  const now = new Date().toISOString();
  const slots: Slot[] = draft.slots.map((s, i) => ({ ...s, id: `s${i + 1}` }));

  const proposal: Proposal = {
    id,
    slug: `${slugify(draft.title) || "proposal"}-${id.slice(0, 4)}`,
    version: 1,
    status: options?.status ?? "open",
    title: draft.title,
    pitch: draft.pitch,
    description: draft.description,
    slots,
    confirmedSlotId: slots.length === 1 ? slots[0].id : null,
    roomSlug: draft.roomSlug,
    expectedPeople: draft.expectedPeople,
    audience: draft.audience,
    tickets: draft.tickets,
    taskListId: null,
    proposerId: author.id,
    proposerName: author.name,
    createdAt: now,
    updatedAt: now,
    comments: [],
    contributions: [],
    rsvps: [],
    revisions: [],
  };

  appendEvent(id, { type: "created", at: now, actorId: author.id, actorName: author.name, proposal });
  return proposal;
}

/** Field-by-field diff, so the thread can show what a revision changed. */
export function diffProposal(before: Proposal, patch: Partial<Proposal>): Revision["changes"] {
  const changes: Revision["changes"] = [];
  const describe = (field: string, value: unknown): string => {
    if (value === null || value === undefined) return "—";
    if (field === "slots") {
      return (value as Slot[]).map((s) => `${s.date} ${s.start} (${s.duration}h)`).join(" · ");
    }
    if (field === "tickets") {
      const t = value as TicketPricing;
      if (!t.eur && !t.tokens) return "free";
      return [
        t.eur ? `€${t.eur}` : null,
        t.tokens ? `${t.tokens} tokens` : null,
        t.freeForMembers ? "free for members" : null,
      ]
        .filter(Boolean)
        .join(" · ");
    }
    return String(value);
  };

  for (const [field, value] of Object.entries(patch)) {
    const from = describe(field, (before as unknown as Record<string, unknown>)[field]);
    const to = describe(field, value);
    if (from !== to) changes.push({ field, from, to });
  }
  return changes;
}

export function reviseProposal(
  id: string,
  patch: Partial<Proposal>,
  actor: { id: string; name: string },
): Proposal | null {
  const before = getProposal(id);
  if (!before) return null;
  const changes = diffProposal(before, patch);
  if (!changes.length) return before;
  appendEvent(before.id, {
    type: "revised",
    at: new Date().toISOString(),
    actorId: actor.id,
    actorName: actor.name,
    patch,
    changes,
  });
  return getProposal(before.id);
}

export function addComment(
  id: string,
  body: string,
  author: { id: string; name: string },
): ProposalComment | null {
  const proposal = getProposal(id);
  if (!proposal) return null;
  const comment: ProposalComment = {
    id: shortId(),
    authorId: author.id,
    authorName: author.name,
    body,
    createdAt: new Date().toISOString(),
  };
  appendEvent(proposal.id, { type: "commented", at: comment.createdAt, comment });
  return comment;
}

export function addContribution(
  id: string,
  contribution: Omit<Contribution, "id" | "createdAt">,
): Contribution | null {
  const proposal = getProposal(id);
  if (!proposal) return null;
  const record: Contribution = {
    ...contribution,
    id: shortId(),
    createdAt: new Date().toISOString(),
  };
  appendEvent(proposal.id, { type: "contributed", at: record.createdAt, contribution: record });
  return record;
}

export function setRsvp(id: string, rsvp: Omit<Rsvp, "createdAt">): Rsvp | null {
  const proposal = getProposal(id);
  if (!proposal) return null;
  const record: Rsvp = { ...rsvp, createdAt: new Date().toISOString() };
  appendEvent(proposal.id, { type: "rsvped", at: record.createdAt, rsvp: record });
  return record;
}

export function linkTaskList(id: string, taskListId: string): void {
  const proposal = getProposal(id);
  if (!proposal) return;
  appendEvent(proposal.id, {
    type: "tasklist_linked",
    at: new Date().toISOString(),
    taskListId,
  });
}

export function setStatus(
  id: string,
  status: ProposalStatus,
  actor: { id: string; name: string },
  options?: { note?: string; confirmedSlotId?: string | null },
): Proposal | null {
  const proposal = getProposal(id);
  if (!proposal) return null;
  appendEvent(proposal.id, {
    type: "status_changed",
    at: new Date().toISOString(),
    actorId: actor.id,
    actorName: actor.name,
    status,
    note: options?.note,
    confirmedSlotId: options?.confirmedSlotId,
  });
  return getProposal(proposal.id);
}

/** The thread: comments, revisions, contributions and decisions in one timeline. */
export type TimelineItem =
  | { kind: "comment"; at: string; comment: ProposalComment }
  | { kind: "revision"; at: string; revision: Revision }
  | { kind: "contribution"; at: string; contribution: Contribution }
  | { kind: "rsvp"; at: string; rsvp: Rsvp }
  | { kind: "status"; at: string; status: ProposalStatus; by: string; note?: string };

export function timelineFor(proposal: Proposal): TimelineItem[] {
  const events = readLog(proposal.id);
  const items: TimelineItem[] = [];
  for (const event of events) {
    switch (event.type) {
      case "commented":
        items.push({ kind: "comment", at: event.at, comment: event.comment });
        break;
      case "contributed":
        items.push({ kind: "contribution", at: event.at, contribution: event.contribution });
        break;
      case "rsvped":
        items.push({ kind: "rsvp", at: event.at, rsvp: event.rsvp });
        break;
      case "status_changed":
        items.push({
          kind: "status",
          at: event.at,
          status: event.status,
          by: event.actorName,
          note: event.note,
        });
        break;
      case "revised": {
        const version =
          items.filter((i) => i.kind === "revision").length + 2; // v1 is the original
        items.push({
          kind: "revision",
          at: event.at,
          revision: {
            version,
            authorId: event.actorId,
            authorName: event.actorName,
            createdAt: event.at,
            changes: event.changes,
          },
        });
        break;
      }
    }
  }
  return items.sort((a, b) => (a.at < b.at ? -1 : 1));
}

export type { Audience };
