/**
 * Writes docs/emails/membership-{reminder,welcome}.*: the membership
 * reminder and welcome emails rendered with {{placeholders}}, for chb to
 * fill in and send (chb holds the members' emails; the website does not).
 * Re-run after changing buildReminderEmail or buildWelcomeEmail:
 *   bun scripts/export-reminder-template.ts
 */
import { writeFileSync } from "fs"

import { buildReminderEmail, type ReminderReason } from "../src/lib/membership-reminder"
import { buildWelcomeEmail } from "../src/lib/membership-welcome"

const reasons: ReminderReason[] = ["payment_failed", "paused", "ended"]
const out: Record<string, { subject: string }> = {}
for (const reason of reasons) {
  for (const organisation of [false, true]) {
    const e = buildReminderEmail({
      name: "{{firstName}}",
      email: "{{email}}",
      reason,
      organisation,
      graceEndsAt: reason === "ended" ? undefined : new Date("2099-12-31T12:00:00Z"),
      renewUrl: "{{renewUrl}}",
      communication: "{{paymentReference}}",
    })
    const name = `membership-reminder.${reason}${organisation ? ".organisation" : ""}`
    const fill = (s: string) => s.replace(/Thursday 31 December/g, "{{graceEndsAtLong}}")
    writeFileSync(`docs/emails/${name}.html`, fill(e.html))
    writeFileSync(`docs/emails/${name}.txt`, fill(e.text))
    out[name] = { subject: e.subject }
  }
}
writeFileSync(
  "docs/emails/membership-reminder.json",
  JSON.stringify(
    {
      _comment: "Generated by scripts/export-reminder-template.ts from src/lib/membership-reminder.ts. Placeholders: {{firstName}}, {{email}}, {{renewUrl}} (https://commonshub.brussels/membership/renew?t=<token signed with RENEW_LINK_SECRET>), {{paymentReference}} (+++…+++, or 'Membership <first name>'), {{graceEndsAtLong}} (e.g. 'Wednesday 21 October', Europe/Brussels). Reasons: payment_failed, paused (both mention the grace period), ended. Send from 'Commons Hub Brussels <hello@commonshub.brussels>', reply-to hello@commonshub.brussels.",
      templates: out,
    },
    null,
    2,
  ),
)
console.log(Object.keys(out).join("\n"))

const welcome: Record<string, { subject: string }> = {}
for (const organisation of [false, true]) {
  const e = buildWelcomeEmail({ name: "{{firstName}}", email: "{{email}}", organisation })
  const name = `membership-welcome${organisation ? ".organisation" : ""}`
  writeFileSync(`docs/emails/${name}.html`, e.html)
  writeFileSync(`docs/emails/${name}.txt`, e.text)
  welcome[name] = { subject: e.subject }
}
writeFileSync(
  "docs/emails/membership-welcome.json",
  JSON.stringify(
    {
      _comment: "Generated by scripts/export-reminder-template.ts from src/lib/membership-welcome.ts. Sent once to a new member, when their first membership payment lands. Placeholders: {{firstName}} (or the organisation's name), {{email}}. Send from 'Commons Hub Brussels <hello@commonshub.brussels>', reply-to hello@commonshub.brussels.",
      templates: welcome,
    },
    null,
    2,
  ),
)
console.log(Object.keys(welcome).join("\n"))
